//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSTourism.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post_tbl
    {
        public int Id { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public Nullable<double> price { get; set; }
        public string location { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string Title { get; set; }
    }
}
